# Generated by Django 6.1 on 2026-08-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField()),
                ('cpassword', models.CharField()),
            ],
        ),
    ]
