# Generated by Django 6.1 on 2026-08-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='cpassword',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
    ]
